### ISSUE TITLE
Adição do link do projeto 

### ISSUE THREAD

**Issue by Dev-Wellington** [ErnstBecker/CollageBook#24]
### No meu fork, eu deixei assim: 
![image](https://github.com/user-attachments/assets/25aad3e1-2e1b-41a2-904c-2666380fff21)

**Comment by ErnstBecker** [comment]
Eu estava utilizando o link no Título do README, mas irei adicionar no About para ficar mais intuitivo. Obrigado pela ideia!

**Comment by ErnstBecker** [comment]
Adicionado!

**Comment by ErnstBecker** [comment]
Adicionado!
