### ISSUE TITLE
updating CollageBook: A Fresh, Engaging Look!

### ISSUE THREAD

**Issue by QuickHarsh** [ErnstBecker/CollageBook#28]
Before: The website had a basic design with minimal visual appeal and no engaging elements.

After: Enhanced with a vibrant background image, colorful links, and improved layout, making it visually striking and inviting, effectively showcasing the artistic theme of the "CollageBook."
see the after look
<img width="1506" alt="update collage2" src="https://github.com/user-attachments/assets/752d848c-a996-4a74-81ac-b128f37883cc">

**Comment by QuickHarsh** [comment]
@ErnstBecker Hii Sir ,Please assign me so that i will make your frontend looks engaging and perfect

**Comment by ErnstBecker** [comment]
Hello! I hope you're doing well. The project is made for the students of "Código Brazuca," so the idea is to keep it simple.
